### ISSUE TITLE
Emmet compatability

### ISSUE THREAD

**Issue by mikerockett** [FilipStryk/Nette-Latte-Neon-for-Sublime-Text-3#2]
Using Latte for the first time, and have installed this package. However, it appears one of the most-used packages, Emmet, is incompatible with this package.

Are there any plans to support it? Or is there a workaround?

**Comment by mikerockett** [comment]
So it appears I can install Smarty to continue using autocompletions in Emmet. I take it Latte is an extension of Smarty? Or are they just similar?

**Comment by mikerockett** [comment]
It's been a while since this issue was opened -- I assume you no longer have time to maintain this package? I'm really battling here, because I'm using Latte again, and it just doesn't mix well with Emmet. Using Smarty is not an option; I can see how they are fundamentally different.

**Comment by Kcko** [comment]
its a possible to use with emmet
